spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  secretKey: "helloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworld"
  expirationDay: 30

password:
  salt: "helloworldisgood"
  salt-cost: 6

swagger:
  server-url: http://localhost:8080

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
